### ISSUE TITLE
补充 antd 中的 icon 的位置修复

### ISSUE THREAD

**Issue by arvinxx** [dewfall123/umi-plugin-tailwindcss#5]
由于 tailwindcss 默认针对 svg 使用了 
```css
svg{
 vertical-align:middle;
}
```
导致 所有 antd 中的 icon 都会往下偏移，就像下图这样

![image](https://user-images.githubusercontent.com/28616219/108847498-bd2cf700-761a-11eb-9607-99ee99dae9f3.png)

现在我每次使用都会在 global 里加一条
```css
svg {
  vertical-align: initial;
}
```
这部分能否集成在插件里？
